### ISSUE TITLE
Change vector internals to a list

### ISSUE THREAD

**Issue by Qazzquimby** [FMTriguero/coding_Fall2020#2]
https://github.com/FMTriguero/coding_Fall2020/blob/95a64cb237c28f2df47dd0e8cc43f2664cc5487a/Main.py#L9-L24

The reasoning is basically that each item in the vector is treated the same, changing only by index, so the work you do on each item is duplicated.

All the dunders can be handled with simple one-liners.

**Comment by FMTriguero** [comment]
I believe I fixed this on commit 2821132 (dont know how to link it here)
